--[[ Teal port of root bighatconfigs.lua ]]

bighat = {}

table.insert(bighat, {x = 0, y = 0, height = 4, graphic = AssetStore.load_image("assets/graphics/standardbighats/standard.png")})

table.insert(bighat, {x = -2, y = -3, height = 5, graphic = AssetStore.load_image("assets/graphics/standardbighats/tyrolean.png")})

table.insert(bighat, {x = -2, y = -2, height = 5, graphic = AssetStore.load_image("assets/graphics/standardbighats/towering1.png")})

table.insert(bighat, {x = -2, y = -8, height = 9, graphic = AssetStore.load_image("assets/graphics/standardbighats/towering2.png")})

table.insert(bighat, {x = -3, y = -1, height = 2, graphic = AssetStore.load_image("assets/graphics/standardbighats/towering3.png")})

table.insert(bighat, {x = -1, y = -7, height = 10, graphic = AssetStore.load_image("assets/graphics/standardbighats/drseuss.png")})

table.insert(bighat, {x = -3, y = -8, height = 8, graphic = AssetStore.load_image("assets/graphics/standardbighats/bird.png")})

table.insert(bighat, {x = -3, y = -2, height = 3, graphic = AssetStore.load_image("assets/graphics/standardbighats/banana.png")})

table.insert(bighat, {x = 1, y = -3, height = 3, graphic = AssetStore.load_image("assets/graphics/standardbighats/beanie.png")})

table.insert(bighat, {x = -1, y = -5, height = 8, graphic = AssetStore.load_image("assets/graphics/standardbighats/toilet.png")})

table.insert(bighat, {x = -1, y = -4, height = 5, graphic = AssetStore.load_image("assets/graphics/standardbighats/indian.png")})

table.insert(bighat, {x = -1, y = -2, height = 4, graphic = AssetStore.load_image("assets/graphics/standardbighats/officerhat.png")})

table.insert(bighat, {x = -2, y = -3, height = 7, graphic = AssetStore.load_image("assets/graphics/standardbighats/crown.png")})

table.insert(bighat, {x = -2, y = -7, height = 10, graphic = AssetStore.load_image("assets/graphics/standardbighats/tophat.png")})

table.insert(bighat, {x = -2, y = 1, height = 3, graphic = AssetStore.load_image("assets/graphics/standardbighats/batter.png")})

table.insert(bighat, {x = -2, y = 0, height = 3, graphic = AssetStore.load_image("assets/graphics/standardbighats/bonk.png")})

table.insert(bighat, {x = 0, y = 0, height = 4, graphic = AssetStore.load_image("assets/graphics/standardbighats/bakerboy.png")})

table.insert(bighat, {x = -3, y = 0, height = 3, graphic = AssetStore.load_image("assets/graphics/standardbighats/troublemaker.png")})

table.insert(bighat, {x = 0, y = 0, height = 4, graphic = AssetStore.load_image("assets/graphics/standardbighats/whoopee.png")})

table.insert(bighat, {x = -1, y = -1, height = 4, graphic = AssetStore.load_image("assets/graphics/standardbighats/milkman.png")})

table.insert(bighat, {x = -2, y = 1, height = 3, graphic = AssetStore.load_image("assets/graphics/standardbighats/bombingrun.png")})

table.insert(bighat, {x = -4, y = 3, height = 0, graphic = AssetStore.load_image("assets/graphics/standardbighats/bonkboy.png")})

table.insert(bighat, {x = -2, y = -1, height = 4, graphic = AssetStore.load_image("assets/graphics/standardbighats/flippedtrilby.png")})

table.insert(bighat, {x = 0, y = -1, height = 3, graphic = AssetStore.load_image("assets/graphics/standardbighats/superfan.png")})

table.insert(bighat, {x = -1, y = -2, height = 4, graphic = AssetStore.load_image("assets/graphics/standardbighats/familiarfez.png")})

table.insert(bighat, {x = -3, y = -1, height = 4, graphic = AssetStore.load_image("assets/graphics/standardbighats/santahat.png")})

table.insert(bighat, {x = -1, y = 0, height = 3, graphic = AssetStore.load_image("assets/graphics/standardbighats/sailor.png")})

table.insert(bighat, {x = -3, y = 0, height = 5, graphic = AssetStore.load_image("assets/graphics/standardbighats/koopa.png")})

table.insert(bighat, {x = -2, y = -5, height = 5, graphic = AssetStore.load_image("assets/graphics/standardbighats/blooper.png")})

table.insert(bighat, {x = -1, y = 1, height = 3, graphic = AssetStore.load_image("assets/graphics/standardbighats/shyguy.png")})

table.insert(bighat, {x = -1, y = 3, height = 4, graphic = AssetStore.load_image("assets/graphics/standardbighats/goodnewseverybody.png")})

table.insert(bighat, {x = -3, y = -1, height = 5, graphic = AssetStore.load_image("assets/graphics/standardbighats/jetset.png")})

table.insert(bighat, {x = -2, y = 0, height = 5, graphic = AssetStore.load_image("assets/graphics/standardbighats/bestpony.png")})
