--[[ Teal port of root hatconfigs.lua ]]

local i
hat = {}

i = 1
hat[i] = {}
hat[i].x = 7 as any
hat[i].y = 2 as any
hat[i].height = 2 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/standard.png")

i = 2
hat[i] = {}
hat[i].x = 5 as any
hat[i].y = -3 as any
hat[i].height = 4 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/tyrolean.png")

i = 3
hat[i] = {}
hat[i].x = 5 as any
hat[i].y = -1 as any
hat[i].height = 4 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/towering1.png")

i = 4
hat[i] = {}
hat[i].x = 5 as any
hat[i].y = -6 as any
hat[i].height = 8 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/towering2.png")

i = 5
hat[i] = {}
hat[i].x = 5 as any
hat[i].y = 1 as any
hat[i].height = 2 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/towering3.png")

i = 6
hat[i] = {}
hat[i].x = 5 as any
hat[i].y = -7 as any
hat[i].height = 10 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/drseuss.png")

i = 7
hat[i] = {}
hat[i].x = 4 as any
hat[i].y = -7 as any
hat[i].height = 8 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/bird.png")

i = 8
hat[i] = {}
hat[i].x = 4 as any
hat[i].y = -1 as any
hat[i].height = 3 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/banana.png")

i = 9
hat[i] = {}
hat[i].x = 7 as any
hat[i].y = -2 as any
hat[i].height = 3 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/beanie.png")

i = 10
hat[i] = {}
hat[i].x = 7 as any
hat[i].y = -5 as any
hat[i].height = 8 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/toilet.png")

i = 11
hat[i] = {}
hat[i].x = 5 as any
hat[i].y = -4 as any
hat[i].height = 5 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/indian.png")

i = 12
hat[i] = {}
hat[i].x = 6 as any
hat[i].y = -1 as any
hat[i].height = 3 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/officerhat.png")

i = 13
hat[i] = {}
hat[i].x = 5 as any
hat[i].y = -3 as any
hat[i].height = 6 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/crown.png")

i = 14
hat[i] = {}
hat[i].x = 5 as any
hat[i].y = -5 as any
hat[i].height = 9 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/tophat.png")

i = 15
hat[i] = {}
hat[i].x = 6 as any
hat[i].y = 1 as any
hat[i].height = 2 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/batter.png")

i = 16
hat[i] = {}
hat[i].x = 6 as any
hat[i].y = 0 as any
hat[i].height = 2 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/bonk.png")

i = 17
hat[i] = {}
hat[i].x = 6 as any
hat[i].y = 0 as any
hat[i].height = 3 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/bakerboy.png")

i = 18
hat[i] = {}
hat[i].x = 5 as any
hat[i].y = 1 as any
hat[i].height = 2 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/troublemaker.png")

i = 19
hat[i] = {}
hat[i].x = 7 as any
hat[i].y = 1 as any
hat[i].height = 3 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/whoopee.png")

i = 20
hat[i] = {}
hat[i].x = 6 as any
hat[i].y = -1 as any
hat[i].height = 4 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/milkman.png")

i = 21
hat[i] = {}
hat[i].x = 6 as any
hat[i].y = 1 as any
hat[i].height = 2 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/bombingrun.png")

i = 22
hat[i] = {}
hat[i].x = 4 as any
hat[i].y = 3 as any
hat[i].height = 0 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/bonkboy.png")

i = 23
hat[i] = {}
hat[i].x = 6 as any
hat[i].y = 0 as any
hat[i].height = 3 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/flippedtrilby.png")

i = 24
hat[i] = {}
hat[i].x = 7 as any
hat[i].y = 0 as any
hat[i].height = 3 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/superfan.png")

i = 25
hat[i] = {}
hat[i].x = 6 as any
hat[i].y = -2 as any
hat[i].height = 4 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/familiarfez.png")

i = 26
hat[i] = {}
hat[i].x = 3 as any
hat[i].y = 0 as any
hat[i].height = 4 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/santahat.png")

i = 27
hat[i] = {}
hat[i].x = 6 as any
hat[i].y = 0 as any
hat[i].height = 2 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/sailor.png")

i = 28
hat[i] = {}
hat[i].x = 3 as any
hat[i].y = -3 as any
hat[i].height = 5 as any
hat[i].graphic = AssetStore.load_image("assets/graphics/standardhats/koopa.png")

table.insert(hat, {x = 5, y = -5, height = 5, graphic = AssetStore.load_image("assets/graphics/standardhats/blooper.png")})

--30:
table.insert(hat, {x = 7, y = 1, height = 2, graphic = AssetStore.load_image("assets/graphics/standardhats/shyguy.png")})

table.insert(hat, {x = 6, y = 4, height = 4, graphic = AssetStore.load_image("assets/graphics/standardhats/goodnewseverybody.png")})

table.insert(hat, {x = 5, y = 1, height = 4, graphic = AssetStore.load_image("assets/graphics/standardhats/jetset.png")})

table.insert(hat, {x = 6, y = 1, height = 4, graphic = AssetStore.load_image("assets/graphics/standardhats/bestpony.png")})