#!/usr/bin/env python3
"""Generate committed dmath LUT + golden vector. Run once; commit outputs.

Do NOT fill SIN via math.sin at game runtime — table must be platform-identical.
"""
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
N = 4096
ATAN_N = 4096
TWO_PI = 2 * math.pi

def main():
    vals = [math.sin(i * TWO_PI / N) for i in range(N)]
    atan_vals = [math.atan(i / (ATAN_N - 1)) for i in range(ATAN_N)]

    def dsin(a, SIN):
        t = a % TWO_PI
        if t < 0:
            t += TWO_PI
        u = t * N / TWO_PI
        i = int(math.floor(u))
        f = u - i
        i0 = i % N
        i1 = (i0 + 1) % N
        return SIN[i0] + (SIN[i1] - SIN[i0]) * f

    golden_angles = [0.0, 0.1, 0.5, 1.0, math.pi/4, math.pi/2, math.pi,
                     3*math.pi/2, 2*math.pi-0.01, -1.234, 10.0, -20.5]

    lut_path = os.path.join(ROOT, "lib", "dmath_lut_data.lua")
    with open(lut_path, "w") as f:
        f.write("-- AUTO-GENERATED by scripts/gen_dmath_lut.py — DO NOT EDIT\n")
        f.write("-- Committed sin/atan tables for bit-identical dmath across platforms.\n")
        f.write("return {\n")
        f.write("  N = %d,\n" % N)
        f.write("  ATAN_N = %d,\n" % ATAN_N)
        f.write("  SIN = {\n")
        for i, v in enumerate(vals):
            f.write("    [%d]=%.17g,\n" % (i, v))
        f.write("  },\n")
        f.write("  ATAN = {\n")
        for i, v in enumerate(atan_vals):
            f.write("    [%d]=%.17g,\n" % (i, v))
        f.write("  },\n")
        f.write("}\n")

    gold_path = os.path.join(ROOT, "tests", "dmath_golden.lua")
    with open(gold_path, "w") as f:
        f.write("-- AUTO-GENERATED golden vector for dmath (bit-identical check)\n")
        f.write("return {\n")
        for a in golden_angles:
            f.write("  {a=%.17g, sin=%.17g, cos=%.17g},\n" % (a, dsin(a, vals), dsin(a + math.pi/2, vals)))
        f.write("}\n")

    print("wrote", lut_path)
    print("wrote", gold_path)

if __name__ == "__main__":
    main()
